{
 "title": "Dashboard ALERTS",
 "description": "The dashborad using Prometheus AlertManager datasource 0.0.6 version.",
 "tags": [ "0.0.1" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hosts Down",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"InstanceDown\"})",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Hosts With High Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"HighMemory\"})",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Hosts High Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"HighDiskUsage\"})",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Process High Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"ProcessHighMemoryUsage\"})",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ALERTS",
     "labelSelector": "server",
     "legendFormat": "{{alertname}} -> {{server}} IP: {{instance}}",
     "target": "Query",
     "type": "heatmap"
    }
   ]
  }
 ]
}